# Generated by Django 3.1.5 on 2021-03-06 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('location', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('is_liked', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='uploads/events/')),
            ],
        ),
    ]
