# Generated by Django 3.1.5 on 2021-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('is_liked', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='uploads/events/')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
