# Generated by Django 3.1.5 on 2021-03-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210306_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='uploads/events/'),
        ),
    ]
